language: java
jdk:
  - openjdk12

services:
  - postgresql

before_install:
  - psql -c 'create database todolist;' -U postgres
  - psql -c 'create database todolisttest;' -U postgres

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - stas.korobeinikov@mail.ru
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="81750b9c-b3b8-4b8b-ba69-498353192d26"


